import asyncio
import structlog
from reportlab.lib.pagesizes import letter
from reportlab.platypus import BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, KeepTogether
from reportlab.platypus.flowables import HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle, Image, PageBreak
import datetime
import html
import hashlib

from app.core.supplement_models import DiscrepancyReport, MaterialBOM
from app.core.inspection_models import InspectionJob
from pathlib import Path

logger = structlog.get_logger("app.services.pdf")
from app.services.pdf.constants import COMPANY_NAME, COMPANY_PHONE, COMPANY_EMAIL, FIELD_DOCS_DIR





class PDFEngine:
    def __init__(self) -> None:
        self.styles = getSampleStyleSheet()
        self._build_custom_styles()
        logger.info("pdf_generator_initialized")


    def _build_custom_styles(self) -> None:
        base_normal = self.styles["Normal"]
        self.custom_styles = {
            "Title": ParagraphStyle(
                "Title", parent=self.styles["Heading1"], fontSize=16, fontName="Helvetica-Bold", alignment=1
            ),
            "SectionHeading": ParagraphStyle(
                "SectionHeading", parent=self.styles["Heading2"], fontSize=11, fontName="Helvetica-Bold", spaceBefore=12, spaceAfter=6
            ),
            "BodyText": ParagraphStyle(
                "BodyText", parent=base_normal, fontSize=10, alignment=4 # 4=TA_JUSTIFY
            ),
            "StatWarning": ParagraphStyle(
                "StatWarning", parent=base_normal, fontSize=10, fontName="Helvetica-Bold", textColor=colors.darkred
            ),
            "FinePrint": ParagraphStyle(
                "FinePrint", parent=base_normal, fontSize=8, textColor=colors.dimgrey, alignment=4
            ),
            "DocControl": ParagraphStyle(
                "DocControl", parent=base_normal, fontSize=10, fontName="Helvetica-Oblique", textColor=colors.darkgrey, alignment=2 # 2=TA_RIGHT
            ),
            "Normal": base_normal,
        }


    def _universal_letterhead(self, canvas, doc) -> None:
        """Universal callback for page headers and footers."""
        canvas.saveState()

        # Header
        canvas.setFont("Helvetica-Bold", 14)
        canvas.drawString(50, 750, COMPANY_NAME)
        canvas.setFont("Helvetica", 10)
        canvas.drawString(50, 735, "123 Roofing Lane, Thomasville, GA 31792")
        canvas.drawString(50, 720, f"Phone: {COMPANY_PHONE} | Email: {COMPANY_EMAIL}")

        import os
        logo_path = "app/static/logo.png"
        if os.path.exists(logo_path):
            try:
                canvas.drawImage(logo_path, 450, 715, width=110, height=45, preserveAspectRatio=True, anchor='ne')
            except Exception as e:
                pass


        # Line under header
        canvas.setStrokeColor(colors.black)
        canvas.setLineWidth(1)
        canvas.line(50, 710, 560, 710)

        # Footer
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.darkgrey)
        job_id = getattr(doc, 'job_id', 'N/A')
        doc_type = getattr(doc, 'doc_type', 'UNKNOWN')
        doc_hash = hashlib.sha256(f"{job_id}|{doc_type}".encode()).hexdigest()[:12]
        canvas.drawString(50, 30, f"Generated by TruckServer — DocHash: {doc_hash}")
        page_num = canvas.getPageNumber()
        canvas.drawRightString(560, 30, f"Page {page_num}")

        canvas.restoreState()


    def _build_signature_block(self, title1: str = "Homeowner Signature", title2: str = "Contractor Signature", include_witness: bool = False):
        """Returns a KeepTogether flowable for clean signature blocks."""
        story: list = []
        story.append(Spacer(1, 30))

        # Two columns: Signature and Date
        data = [
            ["", ""],
            [title1, "Date"],
            ["(Printed Name)", "(MM/DD/YYYY)"],
            ["", ""],
            [title2, "Date"],
            ["(Printed Name)", "(MM/DD/YYYY)"]
        ]

        if include_witness:
            data.extend([
                ["", ""],
                ["Witness / Notary Signature", "Date"],
                ["(Printed Name)", "(MM/DD/YYYY)"]
            ])

        t = Table(data, colWidths=[250, 100])
        style = [
            ('LINEABOVE', (0,1), (0,1), 1, colors.black),
            ('LINEABOVE', (1,1), (1,1), 1, colors.black),
            ('LINEABOVE', (0,4), (0,4), 1, colors.black),
            ('LINEABOVE', (1,4), (1,4), 1, colors.black),
            ('PADDING', (0,0), (-1,-1), 2),
            ('FONTSIZE', (0,2), (1,2), 8),
            ('TEXTCOLOR', (0,2), (1,2), colors.dimgrey),
            ('FONTSIZE', (0,5), (1,5), 8),
            ('TEXTCOLOR', (0,5), (1,5), colors.dimgrey),
            ('BOTTOMPADDING', (0,2), (-1,2), 20),
        ]

        if include_witness:
            style.extend([
                ('LINEABOVE', (0,7), (0,7), 1, colors.black),
                ('LINEABOVE', (1,7), (1,7), 1, colors.black),
                ('FONTSIZE', (0,8), (1,8), 8),
                ('TEXTCOLOR', (0,8), (1,8), colors.dimgrey),
            ])

        t.setStyle(TableStyle(style)) # type: ignore[arg-type]
        story.append(t)

        return KeepTogether(story)


    def _get_doc_template(self, filepath: str, top_margin: int = 144, job_id: str = "N/A", doc_type: str = "DOC") -> BaseDocTemplate:
        """Returns a BaseDocTemplate configured with a Frame that prevents overlapping with the header."""
        doc = BaseDocTemplate(filepath, pagesize=letter, leftMargin=50, rightMargin=50, topMargin=top_margin, bottomMargin=50)
        doc.job_id = job_id # type: ignore[attr-defined]
        doc.doc_type = doc_type # type: ignore[attr-defined]
        # letter height is 792. Leave space at the top.
        frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id='normal')
        template = PageTemplate(id='standard', frames=frame, onPage=self._universal_letterhead)
        doc.addPageTemplates([template])
        return doc


    def _build_metadata_table(self, job: dict) -> Table:
        """Constructs a structured metadata table for the top of documents."""
        address = f"{job.get('address_line1', '')}, {job.get('city', '')}, {job.get('state', '')} {job.get('postal_code', '')}"
        data = [
            ["Job ID:", job.get("id", "N/A")],
            ["Homeowner:", job.get("homeowner_name", "N/A")],
            ["Service Address:", address],
            ["Claim #:", job.get("claim_number", "N/A")],
        ]
        t = Table(data, colWidths=[120, 380])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (0,-1), colors.lightgrey),
            ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.black),
            ('PADDING', (0,0), (-1,-1), 6),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        return t


    def _box_warning(self, title: str, text: str, border_color) -> Table:
        """Wraps a critical legal warning inside a styled Table box."""
        t_data = [
            [Paragraph(title, self.custom_styles["SectionHeading"])],
            [Paragraph(text, self.custom_styles["StatWarning"])]
        ]
        t = Table(t_data, colWidths=[500])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.whitesmoke),
            ('BOX', (0,0), (-1,-1), 1.5, border_color),
            ('PADDING', (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (0,0), 0), # Reduce space between title and text
        ]))
        return t


